# Checksums computed from assets associated with the dcmqi GitHub release
#
# Generated by .github/workflows/update-dcmqi.yml -- do not edit by hand.
# Which of these assets a build uses is decided in dcmqiArchive.cmake.

set(version "1.5.6")

set(linux_filename        "dcmqi-1.5.6-linux.tar.gz")
set(linux_sha256          "eb2743e5c24dec38aafe06612b18d200516f39b8f0d62592a926ca6e8cfb5187")

set(macos_arm64_filename  "dcmqi-1.5.6-mac-arm64.tar.gz")
set(macos_arm64_sha256    "20965b3afcd1d2a878fd3e09e3ee44de655e350d6fe43f9663c93348610f662e")

set(macos_x86_64_filename "dcmqi-1.5.6-mac-x86_64.tar.gz")
set(macos_x86_64_sha256   "6678f2a60547c3a14a9f0376932217c3faee28158b6805c3b89d303df0640747")

set(win64_filename        "dcmqi-1.5.6-win64.zip")
set(win64_sha256          "72f4bf6bc6b265e5843c42436267fb59a8079ca765095f218300d019f9e15e3d")
