# Checksums computed from assets associated with the dcmqi GitHub release
#
# Generated by .github/workflows/update-dcmqi.yml -- do not edit by hand.
# Which of these assets a build uses is decided in dcmqiArchive.cmake.

set(version "1.5.7")

set(linux_filename        "dcmqi-1.5.7-linux.tar.gz")
set(linux_sha256          "7c4f525a122ae5782b1cf7730d8deb9f7d43e218af13104377b615adbced2ddd")

set(linux_arm64_filename  "dcmqi-1.5.7-linux-arm64.tar.gz")
set(linux_arm64_sha256    "dcc605e05eafd6fc92981a16f5ca755f10b1ccceaad0cb2f4343930054ebe3ad")

set(macos_arm64_filename  "dcmqi-1.5.7-mac-arm64.tar.gz")
set(macos_arm64_sha256    "ec17425d3eaa7b58db0924138569508c833e9774ef48052ca85d3e5a1b6cf9b9")

set(macos_x86_64_filename "dcmqi-1.5.7-mac-x86_64.tar.gz")
set(macos_x86_64_sha256   "3d9b88d3e628c3fbcb78f704d08cf438835e248c00601c234002d103c94410ca")

set(win64_filename        "dcmqi-1.5.7-win64.zip")
set(win64_sha256          "dfa86a419ab1ef4af1fbac20720d498a7ffd9f5a7f7f7dd1ad4ac9c138c6b791")
